### ISSUE TITLE
not enough values to unpack error

### ISSUE THREAD

**Issue by reishikin** [gvmossato/subtitles-translator#1]
I got this error when trying to translate a subtitle that has 2 empty lines after the last subtitle line:

translate.py", line 43, in <module>
    num, time, *subs = data_group.split(GROUP_SEPARATOR)
    ^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected at least 2, got 1)

This subtitle file was generated with whisper. When I edit the subtitle to remove the 2 empty lines, it runs just fine. I think it's not a big issue but might affect production value when it comes to batch translating. Thanks for the great tool!

**Comment by S85mario** [comment]
> I got this error when trying to translate a subtitle that has 2 empty lines after the last subtitle line:
> 
> translate.py", line 43, in num, time, *subs = data_group.split(GROUP_SEPARATOR) ^^^^^^^^^^^^^^^^ ValueError: not enough values to unpack (expected at least 2, got 1)
> 
> This subtitle file was generated with whisper. When I edit the subtitle to remove the 2 empty lines, it runs just fine. I think it's not a big issue but might affect production value when it comes to batch translating. Thanks for the great tool!

in my case I solved the problem now it translates perfectly even with empty lines

paste this : 

```
for group_idx, data_group in enumerate(subs_data_groups):
        subs = data_group.split(GROUP_SEPARATOR)

        print(
            f"Translating subtitle group {group_idx+1}/{len(subs_data_groups)}",
            end="\r",
        )

        subs_translated = [translator.translate(text=s) for s in subs]
```

**Comment by gvmossato** [comment]
Thank you, @reishikin, for highlighting this issue and @S85mario for suggesting a solution.

Apologies for the delayed response, I just became aware of the issue today.

I'm addressing it immediately!
